### ISSUE TITLE
fix: exclude specific folders from coverage

### ISSUE THREAD

**Issue by stact** [VeryGoodOpenSource/very_good_test_runner#26]
**Description**
Hi team, we are not able exclude folders from coverage, I don't know if it's a bug, or 
For instance we have generated folder that include our localization

`very_good test --coverage --exclude-coverage "lib/l10n/**"``

**Steps To Reproduce**

1. On your project folder create dummy folder with some dart files
2. Open a terminal
3. "cd" to your flutter project folder
4. Launch the coverage `very_good test --coverage --exclude-coverage "lib/l10n/**"`
5. See the results of the coverage (using vscode flutter coverage extension)

**Expected Behavior**
The folder excluded must be ignored for coverage

**Screenshots**
![image](https://github.com/VeryGoodOpenSource/very_good_test_runner/assets/9899166/bfa53383-71c1-4223-b1c8-3b97d278a385)

**Additional Context**
Tried also to ignore files directly it's not working too

**Comment by tomarra** [comment]
Hi @stact 👋  thanks for opening this issue. From a quick glance at this we were able to reproduce this so were going to look into the `--exclude-coverage` flag and it's implementation.

**Comment by stact** [comment]
Hi @tomarra thank you for reaching out
Unfortunately my knowledge is limited regarding coverage.
I was looking in the past some alternative, maybe this PR can help to adapt the vg test https://github.com/dart-lang/coverage/pull/496

**Comment by stact** [comment]
Ok it seems something is wrong with `very_good test --coverage` firstly generated

This solution solved my issue https://github.com/VeryGoodOpenSource/very_good_cli/issues/496#issuecomment-1303258449

`lcov --remove coverage/lcov.info '**/*_service.dart' -o coverage/lcov.info`

No problem also on ci.
```yaml
build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      coverage_excludes: "**/generated/**" 
```

Thank you for your followup @tomarra maybe it can be removed from the backlog
