### ISSUE TITLE
chore: Confirm Flutter 3.24.0 and Dart 3.5 Support

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_test_runner#28]
**Description**

With the release of Flutter 3.24.0 and Dart 3.5 some things are breaking. Need to review the package and make any necessary fixes.

**Requirements**

- [ ] Package works correctly on Flutter 3.24.0 and Dart 3.5

**Comment by alestiago** [comment]
Moving back to TODO, requires release.

**Comment by alestiago** [comment]
Closing as completed, #31 has been now released.
